language: java

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
# - oraclejdk9

script: mvn install -DskipTests=true

#after_success:
#  - bash <(curl -s https://codecov.io/bash)